### ISSUE TITLE
Finished Blackjack.

### ISSUE THREAD

**Issue by Ross-West** [Ross-West/ICS3U#2]
It's probably terrible, but it's finished, because it's driven me mad enough that there's intrinsic satisfaction in just plain finishing and being done with it.

**Comment by kevindeslauriers** [comment]
Good Work - Ross.  It was very well documented.  There were some issues as you probably knew.  The Big one being that I made a 88 thousand dollar bet when I only had $500.  I won and quite right away before the casino found out I was cheating them.

That said, it was well written and you should ensure you test further and seek out extra help if you are unable to solve the issues.

K 9/10
I 12/15
C 9/10
A 9.5 / 10

87%
